version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@sentry/browser"
    versions:
    - "> 5.11.0, < 5.12"
  - dependency-name: framer-motion
    versions:
    - 3.10.0
    - 3.10.2
    - 3.10.3
    - 3.10.5
    - 3.2.1
    - 3.3.0
    - 3.5.2
    - 3.5.3
    - 3.6.6
    - 3.6.7
    - 3.7.0
    - 3.8.1
    - 3.9.1
    - 3.9.2
    - 4.0.0
    - 4.0.2
    - 4.0.3
    - 4.1.10
    - 4.1.2
    - 4.1.3
    - 4.1.5
    - 4.1.6
    - 4.1.8
    - 4.1.9
  - dependency-name: firebase
    versions:
    - 8.2.10
    - 8.2.4
    - 8.2.5
    - 8.2.6
    - 8.2.7
    - 8.2.8
    - 8.2.9
    - 8.3.0
    - 8.3.1
    - 8.3.2
    - 8.3.3
    - 8.4.1
  - dependency-name: react-use
    versions:
    - 15.3.8
    - 17.0.2
    - 17.1.0
    - 17.1.1
    - 17.2.1
    - 17.2.3
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.0.9
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: lint-staged
    versions:
    - 10.5.3
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: "@inlet/react-pixi"
    versions:
    - 4.1.3
  - dependency-name: chalk
    versions:
    - 4.1.0
